import Head from 'next/head'
import { useRouter } from 'next/router';
import axios from 'axios';

// import Image from 'next/image'
import Numeron from "../Numeron.js";
import History from "../History.js";
import Link from 'next/link'

import styles from '../../styles/Home.module.css'

function leftRoom(num){
  axios
    .get('http://numeronbackend.azurewebsites.net/leftRoom?id='+num)

    .then(res => {
        console.log(res)
        
    })
    .catch(err => {
        console.log(err);
    });
}

export default function Home() {
  const router = useRouter();
  const query = router.query;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="body">
        <Numeron room_id={query.id}/>
        <History/>
        <h3>ルーム{query.id}</h3>
        <Link href="/"><a onClick={()=>leftRoom(query.id)}>退室</a></Link>
        <Link href="https://calm-bay-090786e10.1.azurestaticapps.net/"><a>1人で遊ぶ場合はこちら</a></Link>

      </div>
    </div>
  )
}
